require 'rubygems'
require 'text'

def load
	File.open('soundex_dictionary.dump') do |line|
		return Marshal.load(line)
	end
end

def similar_to(word)
	return load[Text::Soundex.soundex(word)]
end

if ARGV[0]
	word = ARGV[0]
else
	puts "Enter a word"
	print ">> "
	word = gets.chop
end

if ARGV[1]
	threshold = ARGV[1].to_i
else
	threshold = 2
end


puts "Similar sounding words:"
a = similar_to word

$words_by_leven = []

a.each do |word2|
	if Text::Levenshtein.distance(word, word2) < threshold
		$words_by_leven << word2
	end
end

puts $words_by_leven


puts "Saving report to 'report.html'."
html = "<html><head><title>Words that sound like '#{word}'</title></head><body><h1>Words that sound like '#{word}'</h1><p><ul>"

$words_by_leven.each do |words|
	html += "<li>#{words}</li>"
end

html += "</ul></p><p><b>All words:</b><div style='margin-left:2%'>"

a.each do |wurd|
	html += "<span style='font-size:x-small'> (#{wurd}) </span>"
end

html += "</div></p><p><center>Report generated by a program created by <a href='http://aetus.net'>Aetus Designs</center></a></p></body></html>"
File.open('report.html', 'w') do |f|
	f.puts html
end